# Generated by Django 5.0.6 on 2026-09-24 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0008_budget_revisions'),
        ('core', '0001_initial'),
        ('invoices', '0013_invoice_entry_source_and_more'),
        ('vendors', '0014_vendorimportbatch_vendorimportrow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validating', 'Validating'), ('validated', 'Validated'), ('committing', 'Committing'), ('committed', 'Committed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('created_invoices_count', models.PositiveIntegerField(default=0)),
                ('created_vendors_count', models.PositiveIntegerField(default=0)),
                ('total_amount_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('error_summary', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_import_batches', to='core.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoice_import_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('invoice_number', models.CharField(blank=True, max_length=255)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('work_description', models.TextField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('main_head', models.CharField(blank=True, max_length=100)),
                ('budget_head', models.CharField(blank=True, max_length=255)),
                ('sub_category', models.CharField(blank=True, max_length=255)),
                ('vendor_is_new', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('error', 'Error'), ('committed', 'Committed')], default='pending', max_length=20)),
                ('error_messages', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='invoices.invoiceimportbatch')),
                ('created_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_source_rows', to='invoices.invoice')),
                ('resolved_budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_import_rows', to='budgets.budget')),
                ('resolved_budget_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_import_rows', to='budgets.budgetline')),
                ('resolved_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_import_rows', to='budgets.budgetcategory')),
                ('resolved_scope_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_import_rows', to='core.scopenode')),
                ('resolved_subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_import_rows', to='budgets.budgetsubcategory')),
                ('resolved_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='vendors.vendor')),
            ],
            options={
                'db_table': 'invoice_import_rows',
                'ordering': ['row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='invoiceimportbatch',
            index=models.Index(fields=['org', 'status'], name='invoice_imp_org_id_177d76_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceimportrow',
            index=models.Index(fields=['batch', 'status'], name='invoice_imp_batch_i_57234c_idx'),
        ),
    ]
