# Generated by Django 5.0.6 on 2026-09-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_invoiceimportbatch_invoiceimportrow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceimportrow',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('skipped', 'Skipped (Already Imported)'), ('error', 'Error'), ('committed', 'Committed')], default='pending', max_length=20),
        ),
    ]
