# Generated by Django 5.0.6 on 2026-09-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_alter_invoiceimportrow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceimportbatch',
            name='activity_logs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
