# Generated by Django 5.0.6 on 2026-09-03 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('vendors', '0013_vendor_training_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validating', 'Validating'), ('validated', 'Validated'), ('committing', 'Committing'), ('committed', 'Committed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('created_vendors_count', models.PositiveIntegerField(default=0)),
                ('updated_vendors_count', models.PositiveIntegerField(default=0)),
                ('error_summary', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_import_batches', to='core.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vendor_import_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('sap_vendor_id', models.CharField(blank=True, max_length=100)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('scope_node_code', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('pan', models.CharField(blank=True, max_length=20)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('gst_registered', models.BooleanField(blank=True, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc', models.CharField(blank=True, max_length=20)),
                ('beneficiary_name', models.CharField(blank=True, max_length=255)),
                ('preferred_payment_mode', models.CharField(blank=True, max_length=100)),
                ('po_mandate_enabled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('error', 'Error'), ('committed', 'Committed')], default='pending', max_length=20)),
                ('error_messages', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='vendors.vendorimportbatch')),
            ],
            options={
                'db_table': 'vendor_import_rows',
                'ordering': ['row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='vendorimportbatch',
            index=models.Index(fields=['org', 'status'], name='vendor_impo_org_id_787196_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorimportrow',
            index=models.Index(fields=['batch', 'status'], name='vendor_impo_batch_i_eb5d62_idx'),
        ),
    ]
